export function createInitialState(persisted, ensureStat) {
  return {
    screen: "menu",
    siteLanguage: persisted.settings.siteLanguage,
    language: persisted.settings.language,
    mode: persisted.settings.mode,
    focus: persisted.settings.focus,
    startSpeed: persisted.settings.startSpeed,
    highlightTarget: persisted.settings.highlightTarget,
    sound: persisted.settings.sound,
    score: 0,
    isNewBest: false,
    hp: 3,
    streak: 0,
    bestStreak: 0,
    totalHits: 0,
    totalAttempts: 0,
    totalMistakes: 0,
    startedAt: 0,
    finishedAt: 0,
    level: 0,
    lastSummary: null,
    runStats: {},
    active: null,
    keys: [],
    inputQueue: [],
    particles: [],
    shots: [],
    fragments: [],
    shockwaves: [],
    resumeAt: 0,
    pressed: new Map(),
    dictionaries: {},
    assets: { image: null, frames: [], ready: false },
    audio: null,
    lastTime: performance.now(),
    persisted,
    ensureStat,
  };
}
