export function createRunSnapshot(state) {
  return {
    screen: state.screen,
    siteLanguage: state.siteLanguage,
    language: state.language,
    mode: state.mode,
    focus: state.focus,
    startSpeed: state.startSpeed,
    highlightTarget: state.highlightTarget,
    sound: state.sound,
    score: state.score,
    isNewBest: state.isNewBest,
    hp: state.hp,
    streak: state.streak,
    bestStreak: state.bestStreak,
    totalHits: state.totalHits,
    totalAttempts: state.totalAttempts,
    totalMistakes: state.totalMistakes,
    startedAt: state.startedAt,
    finishedAt: state.finishedAt,
    level: state.level,
    lastSummary: state.lastSummary,
    runStats: state.runStats,
    active: state.active,
    resumeAt: state.resumeAt,
  };
}
